# dbt profiles.yml
# This file uses environment variables for security
# For a sample with placeholder credentials, see profiles.yml.example

medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'medical_warehouse') }}"
      schema: staging
      threads: 4
      keepalives_idle: 0
