version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model that cleans and standardizes raw Telegram messages"
    columns:
      - name: message_id
        description: "Unique message identifier from Telegram"
        tests:
          - not_null
      - name: channel_name
        description: "Name of the Telegram channel"
        tests:
          - not_null
      - name: message_date
        description: "Timestamp when message was posted"
        tests:
          - not_null
      - name: message_text
        description: "Text content of the message (cleaned)"
        tests:
          - not_null
      - name: message_length
        description: "Length of message text in characters"
        tests:
          - not_null
      - name: view_count
        description: "Number of views on the message"
        tests:
          - not_null
      - name: forward_count
        description: "Number of times message was forwarded"
        tests:
          - not_null
