version: 2

models:
  - name: dim_channels
    description: |
      Dimension table containing information about each Telegram channel.
      Includes channel classification, posting statistics, and engagement metrics.
    columns:
      - name: channel_key
        description: "Surrogate key for the channel"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Name of the Telegram channel"
        tests:
          - unique
          - not_null
      - name: channel_type
        description: "Classification of channel (Pharmaceutical, Cosmetics, Medical, Other)"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Pharmaceutical', 'Cosmetics', 'Medical', 'Other']
      - name: first_post_date
        description: "Date of the first message from this channel"
        tests:
          - not_null
      - name: last_post_date
        description: "Date of the most recent message from this channel"
        tests:
          - not_null
      - name: total_posts
        description: "Total number of messages from this channel"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: avg_views
        description: "Average number of views per message"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true

  - name: dim_dates
    description: |
      Date dimension table for time-based analysis.
      Includes day, week, month, quarter, year attributes and business logic flags.
    columns:
      - name: date_key
        description: "Surrogate key in YYYYMMDD format"
        tests:
          - unique
          - not_null
      - name: full_date
        description: "Full date value"
        tests:
          - unique
          - not_null
      - name: day_of_week
        description: "Day of week (0=Sunday, 6=Saturday)"
        tests:
          - not_null
      - name: year
        description: "Year"
        tests:
          - not_null
      - name: month
        description: "Month (1-12)"
        tests:
          - not_null
      - name: is_weekend
        description: "Boolean indicating if date is a weekend"
        tests:
          - not_null

  - name: fct_messages
    description: |
      Fact table containing one row per Telegram message.
      Links to dim_channels and dim_dates through foreign keys.
      Contains message content, engagement metrics, and media information.
    columns:
      - name: message_id
        description: "Message identifier (not unique across channels - same message can appear in multiple channels)"
        tests:
          - not_null
      - name: channel_key
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_key
      - name: date_key
        description: "Foreign key to dim_dates"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_dates')
                field: date_key
      - name: message_text
        description: "Text content of the message"
        tests:
          - not_null
      - name: message_length
        description: "Length of message text in characters"
        tests:
          - not_null
      - name: view_count
        description: "Number of views on the message"
        tests:
          - not_null
      - name: forward_count
        description: "Number of times message was forwarded"
        tests:
          - not_null
      - name: has_image
        description: "Boolean indicating if message has an image"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - message_id
            - channel_key